cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart/', views.hx_menu_cart, name="hx_menu_cart"),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),
    path('hx_checkout_button/', views.hx_checkout_button, name="hx_checkout_button"),
]

my_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name='order'

urlpatterns = [
    path('start_order/', views.start_order, name='start_order')
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .cart import Cart
from product.models import Product

def cart(request):
    cart = Cart(request)

    return render(request, 'cart/cart.html')

def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)

    return render(request, 'cart/partials/menu_cart.html')

def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == "increment":
        cart.add(product_id, 1, True)
    else:
        cart.add(product_id, -1, True)
    
    product = Product.objects.get(pk=product_id)
    quantity = cart.get_item(product_id)

    if quantity:
        quantity = quantity['quantity']

        item = {
            'product': {
                'id': product.id,
                'name': product.name,
                'image': product.image,
                'slug': product.slug,
                'get_thumbnail': product.get_thumbnail(),
                'price': product.price
            },
            'total_price': (quantity * product.price),
            'quantity': quantity,
        }
    else:
        item = None

    response = render(request, 'cart/partials/cart_item.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-cart'

    return response
    
def hx_menu_cart(request):
    return render(request, 'cart/partials/menu_cart.html')

def hx_cart_total(request):
    return render(request, 'cart/partials/cart_total.html')

def hx_checkout_button(request):
    return render(request, 'cart/partials/hx_checkout_button.html')

@login_required 
def checkout(request):
    return render(request, 'cart/checkout.html')

cart/templates/cart/cart.html
{% extends "core/base.html" %}

{% block title %}Cart{% endblock %}

{% block content %}
    <h1 class="max-w-6xl mx-auto text-3xl text-center mt-4 font-semibold">Your Cart</h1>
    <main class="max-w-6xl mx-auto flex  items-start space-x-6">
        <div class="w-full lg:w-3/4 bg-gray-200 mt-3 rounded-xl">
            {% if cart %}
                {% for item in cart %}
                    {% include "cart/partials/cart_item.html" %}
                {% endfor %}
            {% else %}
                <h2 class= "text-xl text-center p-2">Your Cart Is Emtype</h2>
            {% endif %}
        </div>

        
        <div class="w-full lg:w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
            <h2 class="uppercase text-lg mb-5">Summary</h2>

            <div class="mb-6 flex justify-between">
                <span class="font-semibold">Total Price:</span>
                <span
                    hx-get="{% url 'cart:hx_cart_total' %}"
                    hx-trigger="update-menu-cart from:body"
                    hx-swap="innerHTML"
                >
                {% include 'cart/partials/cart_total.html' %}            
                </span>
            </div>
            
            <div
                hx-get="{% url 'cart:hx_checkout_button' %}"
                hx-trigger="update-menu-cart from:body"
                hx-swap="innerHTML"    
            >
            {% include "cart/partials/hx_checkout_button.html" %}
            </div>
        </div>
    </main>
{% endblock %}

cart/templates/cart/checkout.html
{% extends 'core/base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
<h1 class="max-w-6xl mx-auto text-3xl text-center mt-4 font-semibold">Checkout</h1>
<div class="max-w-6xl mx-auto py-6 px-6 xl:px-0">
    <form method="post" action="{% url 'order:start_order' %}" class="flex flex-wrap items-start">
        {% csrf_token %}
        <div class="products w-full lg:w-3/4 ">
            <div class="w-full pr-6">
                <div class="mb-6 p-6 bg-gray-200 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Shipping information</h2>

                    <div class="flex space-x-6">
                        <div class="w-1/2 mb-4">
                            <label class="inline-block mb-2">First name</label>
                            <input name="first_name" type="text" class="w-full p-5 rounded-xl" value="{{ request.user.first_name }}">
                        </div>

                        <div class="w-1/2 mb-4">
                            <label class="inline-block mb-2">Last name</label>
                            <input name="last_name" type="text" class="w-full p-5 rounded-xl" value="{{ request.user.last_name }}">
                        </div>
                    </div>

                    <div class="mb-4">
                        <label class="inline-block mb-2">Address</label>
                        <input name="address" type="text" class="w-full p-5 rounded-xl">
                    </div>
                </div>

                <div class="mb-6 p-6 bg-gray-200 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Contact information</h2>

                    <div class="mb-4">
                        <label class="inline-block mb-2">Email</label>
                        <input name="email" type="email" class="w-full p-5 rounded-xl" value="{{ request.user.email }}">
                    </div>

                    <div class="mb-4">
                        <label class="inline-block mb-2">Phone</label>
                        <input name="phone" type="phone" class="w-full p-5 rounded-xl">
                    </div>
                </div>

                <div class="mb-6 p-6 bg-gray-200 rounded-xl">
                    <h2 class="mb-5 uppercase text-lg">Payment information</h2>
                    <p class="text-center text-gray-400">Comming soon</p>
                </div>
            </div>
        </div>

        <div class="summary w-full lg:w-1/4 p-6 bg-gray-100 rounded-xl">
            <h2 class="uppercase text-lg mb-5">Summary</h2>
    
            <div class="mb-6 flex justify-between">
                <span class="font-semibold">Total</span>
                <span>${{ cart.total_price }}</span>
            </div>
    
            <button
                class="inline-block px-8 py-4 rounded-xl bg-purple-500 hover:bg-purple-700 text-white"
            >
                Confirm checkout
            </button>
        </div>
    </form>
</div>
{% endblock %}