cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart/', views.hx_menu_cart, name="hx_menu_cart"),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),
    path('hx_checkout_button/', views.hx_checkout_button, name="hx_checkout_button"),
]

core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

# namespace
app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('products/', views.shop, name='shop'),
    path('about_me/', views.about_me, name='about_me'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('edit-account/', views.edit_account, name='edit_account'),
    
]

my_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

# namespace
app_name = 'product'

urlpatterns = [
    path('<slug:slug>/', views.detail, name='detail'),
]   

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

INPUT_FORM = 'w-full py-4 px-6 rounded-xl'

class SignupFrom(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your username",
        'class': INPUT_FORM
    }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your first name",
        'class': INPUT_FORM
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your last name",
        'class': INPUT_FORM
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': "Your email",
        'class': INPUT_FORM
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Your password",
        'class': INPUT_FORM
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Repeat passoword",
        'class': INPUT_FORM
    }))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your username",
        'class': INPUT_FORM
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "Your password",
        'class': INPUT_FORM
    }))

core/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from product.models import Product, Category
from order.models import Order, OrderItem
from .forms import SignupFrom

def homepage(request):
    featured_products = Product.objects.all()[:4]
    categories = Category.objects.all()[:4]
    new_arrival_products = Product.objects.all()[:4]

    return render(request, 'core/homepage.html', {
        'featured_products': featured_products,
        'categories': categories,
        'new_arrival_products': new_arrival_products,
        
    })

def shop(request):
    products = Product.objects.all()
    categories = Category.objects.all()

    search = request.GET.get('search', '')
    if search:
        products = products.filter(Q(name__icontains=search) | Q(description__icontains=search))


    active_category = request.GET.get('category' ,'')
    if active_category:
        products = products.filter(category__slug=active_category)
    

    return render(request, "core/shop.html", {
        'products': products,
        'categories':categories,
        'active_category': active_category,
    })

def about_me(request):

    return render(request, 'core/about_me.html')

def signup(request):
    if request.method == "POST":
        form = SignupFrom(request.POST)

        if form.is_valid:
            form.save()

            return redirect('/login/')

    else:
        form = SignupFrom()

    return render(request, 'core/signup.html', {
        'form': form,
    })
    

@login_required
def myaccount(request):
    
    return render(request, 'core/myaccount.html')

@login_required
def edit_account(request):
    if request.method == "POST":
        user = request.user

        user.username = request.POST.get('username')
        user.fist_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.email = request.POST.get('email')
        user.save()

        return redirect('core:myaccount')

    return render(request, 'core/edit_account.html')
    

core/templates/core/about_me.html
{% extends "core/base.html" %}

{% block title %}About Me{% endblock %}

{% block header%}
    <header class="pb-28">
        <h1 class="mt-16 text-center text-3xl font-bold text-violet-100">About Me</h1>
    </header>
{% endblock %}

{% block content %}
    <main class="max-w-6xl mx-auto mt-8 flex space-x-8">
        {% load static %}
        <img src="{% static 'background/me.jpg' %}" class="w-1/2 rounded-xl">

        <div class="w-1/2">
            <h1 class="text-2xl text-fuchsia-500">Story</h1>
            <p>Lorem</p>
        </div>
    </main>
{% endblock %}

core/templates/core/base.html
<!doctype html>

<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="https://cdn.tailwindcss.com"></script>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>


        {% load static %}
        <link rel='icon' href="{% static 'background/favicon.png' %}"/>
        <title>{% block title %}{% endblock %} | HHStore</title>

        {% comment %} goodlefont {% endcomment %}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;700&display=swap" rel="stylesheet">
        {% comment %} fontawesome {% endcomment %}
        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body>
        <div class="bg-gradient-to-r from-purple-500 to-pink-500">
            <nav class="p-8 flex justify-between">
                <div class="">
                    <a href="{% url 'core:homepage' %}">
                        <h2 class="text-xl text-white font-bold">HHStore</h2>
                    </a>
                </div>

                <div class="flex flex-warp space-x-6 font-medium">
                    <a href="{% url 'core:homepage' %}">Home</a>

                    <a href="{% url 'core:shop' %}">All Products</a>

                    <a href="{% url 'core:about_me' %}">About Me</a>

                    <a href="#">Contact</a>
                    
                    <a 
                        href="{% if not request.user.is_authenticated %}{% url 'core:login' %}{% else %}{% url 'core:myaccount' %}{% endif %}" 
                        class=""
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>                          
                    </a>
                    
                    <div
                        hx-get="{% url 'cart:hx_menu_cart' %}"
                        hx-trigger="update-menu-cart from:body"
                        hx-swap="innerHTML"
                    >
                        {% include "cart/partials/menu_cart.html" %}
                    </div>
                    
                </div>
            </nav>

            {% block header %}{% endblock %}
        </div>

        {% block content %}
        {% endblock %}

        <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    </body>

    <footer class="bg-zinc-900 p-10 mt-10">
        <div class="flex justify-between">
            <h2 class="text-xl text-lime-700 font-bold">HHStore</h2>

            <div class="flex space-x-4 text-lime-700 text-xl">
                <a href="#"><i class="fa-brands fa-facebook"></i></a>
                <a href="#"><i class="fa-brands fa-square-instagram"></i></a>
                <a href="#"><i class="fa-brands fa-twitter"></i></a>
            </div>
        </div>

        <div class="mt-6 flex items-center justify-center text-white space-x-10">
            <a href="{% url 'core:homepage' %}">Home</a>
            <a href="{% url 'core:shop' %}">All Products</a>
            <a href="{% url 'core:about_me' %}">About Me</a>
            <a href="{% url 'cart:cart' %}">Cart</a>
            <a href="#">Contact</a>
        </div>

        <hr class="w-full h-1 mx-auto mt-12 bg-gray-100 border-0 rounded  dark:bg-gray-700">

        <div class="mt-6 flex items-center justify-center text-white space-x-6">
            <a href="#" class="underline">Privacy Policy</a>
            <a href="#" class="underline">Terms of Service</a>
            <a href="#" class="underline">Cookies Settings</a>
        </div>
    </footer>
</html>

core/templates/core/edit_account.html
{% extends 'core/base.html' %}

{% block title %}Edit Account{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 rounded-xl">
    <h1 class="mb-6 text-3xl text-center font-semibold">Edit account</h1>

    <form method="post" action="." class="border-2 p-4 rounded-xl border-cyan-500">
        {% csrf_token %}

        <div>
            <label>Username</label>
            <input name="username" value="{{ request.user.username }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-200 rounded-xl">
        </div>

        <div class="mb-3 flex space-x-4">
            <div class="w-1/2">
                <label>First name</label>
                <input name="first_name" value="{{ request.user.first_name }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-200 rounded-xl">
            </div>

            <div class="w-1/2">
                <label>Last name</label>
                <input name="last_name" value="{{ request.user.last_name }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-200 rounded-xl">
            </div>
        </div>

        <div>
            <label>E-mail</label>
            <input name="email" value="{{ request.user.email }}" type="email" class="w-full mt-2 py-4 px-6 bg-gray-200 rounded-xl">
        </div>

        <button class="mt-4 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/homepage.html
{% extends "core/base.html" %}

{% block title %}Home Page{% endblock %}

{% block header%}
    <header class="pb-28">
        <h1 class="mt-16 text-center text-3xl font-bold text-violet-100">Furniture That Fits Your Life, Delivered </br> to Your Door.</h1>
    </header>
{% endblock %}

{% block content %}
    <main class="max-w-6xl mx-auto">
        <div class="mt-16 mx-auto py-2 px-6 xl:px-0">
            <h2 class="text-center font-semibold text-lime-700 text-xl">Product Features</h2>
            
            <div class="mt-8 grid grid-cols-4 gap-4">
                {% for product in featured_products %}
                    {% include "product/partials/list_product.html" %}
                {% endfor %}
            </div>
        </div>

        <div class="mt-16 mx-auto py-2 px-6 xl:px-0">
            <h2 class="text-center font-semibold text-lime-700 text-xl">Categories</h2>
            <div class="mt-8 flex items-center space-x-4">
                {% for category in categories %}
                    {% include "product/partials/list_category.html" %}
                {% endfor %}
            </div>
        </div>

        <div class="mt-16 mx-auto py-2 px-6 xl:px-0">
            <h2 class="text-center font-semibold text-lime-700 text-xl">New Arrivals</h2>
            <div class="mt-8 grid grid-cols-4 gap-4">
                {% for product in new_arrival_products %}
                    {% include "product/partials/list_product.html" %}
                {% endfor %}
            </div>
        </div>

        <div class="mt-16 max-w-6xl mx-auto py-2 px-6">
            <div class="flex space-x-6">
                <div class="w-full lg:w-1/2">
                    {% load static %}
                    <img src="{% static 'background/furniture_2.jpg' %}" class="rounded-xl"/>
                </div>

                <div class="w-full lg:w-1/2">
                    <h1 class="text-2xl font-semibold text-lime-700">Why Choose Us?</h1>
                    <p class="mt-4">
                        We believe that furniture sould be a reflection of your unique personality and lifestyle.
                        That's why we curate an exquisite collection of hanhpicked pieces, each carefully selected
                        for its craftsmanship, design, and durability.
                    </p>
                    <div class="mt-4 grid grid-cols-2 gap-x-2 gap-y-4">
                        <span><i class="fa-solid fa-check text-lime-700"></i> Quick Shipping</span>
                        <span><i class="fa-solid fa-check text-lime-700"></i> Affordability</span>
                        <span><i class="fa-solid fa-check text-lime-700"></i> Quality Assurance</span>
                        <span><i class="fa-solid fa-check text-lime-700"></i> Money-Back Guarantee</span>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login up{% endblock %}

{% block content %}
    <main class="w-1/2 my-6 mx-auto p-6 bg-gray-200 rounded-xl">
        <h1 class="mb-6 text-3xl">Login in</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>


            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="flex justify-between">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Login</button>
                <a href="{% url 'core:signup' %}" class="mt-2 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Signup <i class="fa-solid fa-user-plus"></i></a>
            </div>
        </form>
    </main>
{% endblock %}

core/templates/core/myaccount.html
{% extends "core/base.html" %}

{% block title %}Shop{% endblock %}

{% block content %}
    <main class="max-w-6xl mx-auto">
        <div class="mt-4 space-y-4">
            <h2 class="text-xl font-semibold">Username: {{ request.user.username }}</h2>
            <p>First name: {{request.user.first_name }}</p>
            <p>Last name: {{ request.user.last_name }}</p>
            <p>Email: {{ request.user.email }}</p>

            <a href="{% url 'core:edit_account' %}" class="inline-block mt-4 p-2 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Edit Account</a>
            <a href="{% url 'core:logout' %}" class="inline-block mt-4 p-2 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Log out</a>
        </div>  
        
        <h2 class="m-6 text-2xl font-semibold text-center text-violet-600">My orders</h2>

        {% for order in request.user.orders.all %}
            <div class="w-full mb-6 p-6 flex flex-wrap bg-gray-200 rounded-xl">
                <div class="mb-6 flex justify-between">
                    <a href="#">Order id: {{ order.id }}</a>
                </div>

                <div class="mb-6 w-full">
                    {% for item in order.items.all %}
                        <div class="product mb-6 flex pr-6">
                            <a href="{% url 'product:detail' item.product.slug %}" class="w-1/4">
                                <img class="hover:shadow-lg rounded-xl" src="{{ item.product.get_thumbnail }}">
                            </a>

                            <div class="w-3/4 pl-6">
                                <div class="flex justify-between">
                                    <a href="{% url 'product:detail' item.product.slug %}" class="text-lg"><strong>{{ item.product.name }}</strong></a>

                                    <p class="mb-6 pt-1 text-gray-400">Total: ${{ item.price}}</p>
                                </div>

                                <hr class="w-full h-1 mx-auto bg-gray-100 rounded dark:bg-gray-700">
                                <div class="flex justify-between mt-6">
                                    <div class="">
                                        Quantity: {{ item.quantity }}
                                    </div>
                                    <div>Price: {{ item.product.price }}</div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div>
                    <p class="text-lg">Date: {{ order.created_at|date:'d-m-Y' }}</p>
                    <p class="text-lg">Total orders: <strong>${{ order.total_price }}</strong></p>
                </div>
            </div>
        {% endfor %}
    </main>
{% endblock %}

core/templates/core/shop.html
{% extends "core/base.html" %}

{% block title %}Shop{% endblock %}

{% block content %}
    <main class="max-w-6xl mx-auto flex mt-4">
        <aside class="w-full lg:w-1/4">
            <h2 class="mt-3 text-xl">SEARCH</h2>

            <form method='get' action='.'>
                <div class="mt-3 flex">
                    <input type="text" name="search" placeholder="Search..." class="p-3 border-0 bg-gray-200"/>
                    
                    <button class="p-3 bg-gray-200">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 15.75l-2.489-2.489m0 0a3.375 3.375 0 10-4.773-4.773 3.375 3.375 0 004.774 4.774zM21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>                          
                    </button>
                </div>
            </form>

            <h2 class="mt-6 text-xl">CATEGORIES</h2>
            <ul class="mt-3 space-y-2">
                <li><a 
                        href="{% url 'core:shop' %}"
                        class="{% if not active_category %}text-fuchsia-500{% else %}text-gray-500{% endif %}"
                    >
                        All Categories
                    </a>
                </li>

                {% for category in categories %}
                    <li><a href="{% url 'core:shop' %}?category={{ category.slug }}" class="{% if category.slug == active_category %}text-fuchsia-500{% else %}text-gray-500{% endif %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </aside>

        <div class="w-full lg:w-3/4 border-2 border-cyan-500 rounded-xl p-2">
            <div class="grid grid-cols-3 gap-4" id="shop_list_product">
                {% for product in products %}
                    {% include "product/partials/list_product.html" %}
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<main class="w-1/2 my-6 mx-auto p-6 bg-gray-200 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3 flex space-x-4">
            <div class="w-1/2">
                <label class="inline-block mb-2">First name</label><br>
                {{ form.first_name }}
            </div>
            <div class="w-1/2">
                <label class="inline-block mb-2">Last name</label><br>
                {{ form.last_name }}
            </div> 
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat passowrd</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-2 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</main>
{% endblock %}