cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart/', views.hx_menu_cart, name="hx_menu_cart"),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),
    path('hx_checkout_button/', views.hx_checkout_button, name="hx_checkout_button"),
]

core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

# namespace
app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('products/', views.shop, name='shop'),
    path('about_me/', views.about_me, name='about_me'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('edit-account/', views.edit_account, name='edit_account'),
    
]

my_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

# namespace
app_name = 'product'

urlpatterns = [
    path('<slug:slug>/', views.detail, name='detail'),
]   

product/models.py
from django.db import models
from django.core.files import File
from django.contrib.auth.models import User

from io import BytesIO
from PIL import Image

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    image = models.ImageField(upload_to="category_image", blank=True, null=True)
    thumbnail = models.ImageField(upload_to='thumbnail_image', blank=True, null=True)

    class Meta:
        ordering = ('name', )
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    
    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/300x200.jpg'
    
    def make_thumbnail(self, image, size=(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img = img.resize(size)

        thumb_io = BytesIO()
        img.save(thumb_io, "JPEG", quality=85)

        thumbnail = File(thumb_io, name=image.name)

        return thumbnail
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField(max_length=2000)
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="product_image", blank=True, null=True)
    thumbnail = models.ImageField(upload_to='thumbnail_image', blank=True, null=True)

    class Meta:
        ordering = ('-created_at', )

    def __str__(self):
        return self.name
    
    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/300x200.jpg'
    
    def make_thumbnail(self, image, size=(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img = img.resize(size)

        thumb_io = BytesIO()
        img.save(thumb_io, "JPEG", quality=85)

        thumbnail = File(thumb_io, name=image.name)

        return thumbnail
    
    def get_rating(self):
        reviews_total = 0

        for review in self.reviews.all():
            reviews_total += review.rating
        
        if reviews_total > 0:
            return reviews_total / self.reviews.count()
        
        return 0
class Review(models.Model):
    product = models.ForeignKey(Product, related_name="reviews", on_delete=models.CASCADE)
    rating = models.IntegerField(default=3)
    content = models.TextField()
    created_by = models.ForeignKey(User, related_name="reviews", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

product/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Product, Review


def detail(request, slug):
    product = get_object_or_404(Product, slug=slug)

    if request.method == 'POST':
        rating = request.POST.get('rating', 3)
        content = request.POST.get('content', '')

        if content:
            reviews = Review.objects.filter(created_by=request.user, product=product)

            if reviews.count() > 0:
                review = reviews.first()
                review.rating = rating
                review.content = content
                review.save()
            else:
                review = Review.objects.create(
                    product=product,
                    rating=rating,
                    content=content,
                    created_by=request.user
                )

            return redirect('product:detail', slug=slug)

    return render(request, 'product/detail.html', {'product': product})

def hx_product_list(request):
    products = Product.objects.all()

    return render(request, 'product/partials/list_product.html', {
        'products': products,
    })

product/templates/product/detail.html
{% extends "core/base.html" %}

{% block title %}{{ product.name }}{% endblock %}


{% block content %}
    <main class="mt-10 max-w-6xl mx-auto">
        <div class="flex space-x-6">
            <div class="w-full lg:w-1/2">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="rounded-xl"/>
                {% else %}
                    <img = src="https://via.placeholder.com/400x400.jpg"/>
                {% endif %}
            </div>

            <div class="w-full lg:w-1/2 bg-gray-100 p-4 rounded-xl">
                <h2 class="text-2xl">{{ product.name }}</h2>
                <p class="mt-2">Price: ${{ product.price }}</h2> 

                {% if product.get_rating > 0 %}
                    <p class="mt-1 text-gray-400">Rating: {{ product.get_rating }} / 6</p>
                {% endif %}
                
                {% if product.description %}
                    <p class="mt-6 text-gray-700 bg-gray-200 p-2 rounded-xl">{{ product.description }}</p>
                {% endif %}
    
                <a
                    href="#"
                    class="mt-6 inline-block px-8 py-4 rounded-xl bg-purple-500 text-white hover:bg-purple-800"
                    hx-get="{% url 'cart:add_to_cart' product.id %}"
                    hx-target="#menu-cart-button" 
                    hx-swap="outerHTML"
                >
                Add to cart
                </a>
            </div>
        </div>

        
        <div class="w-full mt-6">
            <h2 class="text-xl">Reviews</h2>
    
            {% if request.user.is_authenticated %}
                <form method="post" action="." class="mt-2 p-6 bg-gray-200 rounded-xl">
                    {% csrf_token %}
    
                    <div class="flex justify-between space-x-10">
                        <div class="w-1/2 space-y-2">
                            <label>Comment</label><br>
                            <input type='text' name="content" class="w-full rounded-xl p-2"></input>
                        </div>

                        <div class="w-1/2 space-y-2">
                            <label class="">Rating</label><br>
                            <select name="rating">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3" selected>3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                            </select>
                        </div>
                    </div>
    
                    <div class="mt-6">
                        <button class="py-2 px-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
                    </div>
                </form>
            {% else %}
                <a href="{% url 'core:login' %}" class="p-2 mt-4 bg-green-500 rounded-xl inline-block">Login to review</a>
            {% endif %}
    
            {% if product.reviews.all %}
                <div class="mt-4 p-2 bg-gray-200 rounded-xl">
                    {% for review in product.reviews.all %}
                        <div class="px-4 mb-4">
                            <strong>User: </strong>{{ review.created_by.first_name }} {{ review.created_by.last_name}} -- 
                            <strong>Date:</strong> {{ review.created_at|date:"d/m/Y" }} --  
                            <strong>Rating:</strong> {{ review.rating }}/6</br>
                            <strong>Comment: </strong>{{ review.content }}
                            <hr class="w-full h-1 mx-auto bg-gray-100 rounded dark:bg-gray-700">
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="mt-4 p-2 bg-gray-200 rounded-xl">
                    <p class="text-gray-800 text-center">Emtype reivew</p>
                </div>
            {% endif %}
        </div>
    </main>
{% endblock %}