cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', views.update_cart, name='update_cart'),
    path('hx_menu_cart/', views.hx_menu_cart, name="hx_menu_cart"),
    path('hx_cart_total/', views.hx_cart_total, name='hx_cart_total'),
    path('hx_checkout_button/', views.hx_checkout_button, name="hx_checkout_button"),
]

my_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .cart import Cart
from product.models import Product

def cart(request):
    cart = Cart(request)

    return render(request, 'cart/cart.html')

def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)

    return render(request, 'cart/partials/menu_cart.html')

def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == "increment":
        cart.add(product_id, 1, True)
    else:
        cart.add(product_id, -1, True)
    
    product = Product.objects.get(pk=product_id)
    quantity = cart.get_item(product_id)

    if quantity:
        quantity = quantity['quantity']

        item = {
            'product': {
                'id': product.id,
                'name': product.name,
                'image': product.image,
                'slug': product.slug,
                'get_thumbnail': product.get_thumbnail(),
                'price': product.price
            },
            'total_price': (quantity * product.price),
            'quantity': quantity,
        }
    else:
        item = None

    response = render(request, 'cart/partials/cart_item.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-cart'

    return response
    
def hx_menu_cart(request):
    return render(request, 'cart/partials/menu_cart.html')

def hx_cart_total(request):
    return render(request, 'cart/partials/cart_total.html')

def hx_checkout_button(request):
    return render(request, 'cart/partials/hx_checkout_button.html')

@login_required 
def checkout(request):
    return render(request, 'cart/checkout.html')

cart/templates/cart/partials/cart_item.html
{% if item %}
    <div class="product mb-6 p-4 flex pr-6" id="cart-item-{{ item.product.id }}">
        <a href="#" class="w-1/4">
            <img class="hover:shadow-lg rounded-xl" src="{{ item.product.get_thumbnail }}">
        </a>

        <div class="w-3/4 pl-6">
            <div class="flex justify-between">
                <a href="#" class="text-lg">{{ item.product.name }}</a>

                <span class="mb-6 pt-1 text-gray-400">${{ item.total_price }}</span>
            </div>

            <hr class="w-full h-1 mx-auto bg-gray-100 rounded dark:bg-gray-700">

            <div class="quantity mt-6 flex items-center space-x-4">
                <a 
                    href="#"
                    class="p-3 bg-gray-100"
                    hx-get="{% url 'cart:update_cart' item.product.id 'decrement' %}"
                    hx-target = "#cart-item-{{ item.product.id }}"
                    hx-swap="outerHTML"
                >-</a>
                <span>{{ item.quantity }}</span>
                <a 
                    href="#"
                    class="p-3 bg-gray-100"
                    hx-get="{% url 'cart:update_cart' item.product.id 'increment' %}"
                    hx-target = "#cart-item-{{ item.product.id }}"
                    hx-swap="outerHTML"
                >+</a>
            </div>
        </div>
    </div>
{% elif not cart.cart %}
    <h2 class= "text-xl text-center p-2">Your Cart Is Emtype</h2>
{% endif %}

cart/templates/cart/partials/cart_total.html
<span class="total_price">${{ cart.total_price }}</span>

cart/templates/cart/partials/hx_checkout_button.html
{% if cart.cart %}
    <a href="{% url 'cart:checkout' %}" class="inline-block px-8 py-4 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">Checkout</a>
{% endif %}

cart/templates/cart/partials/menu_cart.html
<a href="{% url 'cart:cart' %}" id="menu-cart-button" class="relative">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
    </svg>

    <span class="p-2 absolute -top-4 -right-3 bg-indigo-500 text-white text-xs rounded-full">{{ cart|length }}</span>
</a>